### ISSUE TITLE
Suggestion: Rename master branch

### ISSUE THREAD

**Issue by magdapoppins** [turkupy/turkupy.github.io#22]
Since it isn't anymore considered a good practice to use the word "master", I suggest changing the main branch to something else (maybe "main"). This requires updating the related github action as well as renaming the branch itself.

**Comment by eevajonnapanula** [comment]
I totally agree! However, one thing that needs to be checked as well is that will the deployment work after renaming, as organisation pages required `master` branch to be the page source to work. There should be some answers to this in the docs (I didn't have time to check yet)
