### ISSUE TITLE
Finnish translations for the site (site texts)

### ISSUE THREAD

**Issue by eevajonnapanula** [turkupy/turkupy.github.io#30]
We need Finnish translations for texts in the website. See more information here: [About translations](https://github.com/turkupy/turkupy.github.io/blob/dev/docs/translations.md)

So what needs to be done, is to add Finnish translations to [translations.json](https://github.com/turkupy/turkupy.github.io/blob/dev/src/utils/translations/translations.json).

After adding the texts, you can see these translations locally in `https://localhost:8000/fi/`

**Comment by sjarva** [comment]
Created a PR to fix this 💖 📚
