### ISSUE TITLE
[Translations] Effective Python reading circle - fi

### ISSUE THREAD

**Issue by eevajonnapanula** [turkupy/turkupy.github.io#35]
**What event the translation is missing for:**
[Effective Python reading circle](https://github.com/turkupy/turkupy.github.io/blob/dev/content/events/fi/effective-python/index.md)

**Comment by kzrantan** [comment]
Jätän kommentin

**Comment by eevajonnapanula** [comment]
so this is assigned to @kzrantan (I'm guessing there's something in your settings and I cannot assing you 🤔 )

**Comment by kzrantan** [comment]
Känsin yhden tekstin. Tulihan teksti perille? Siinä oli pari sanaa, joita en osannut suomentaa gotcha ja pull request, mitäköhän tämä on suomalaisessa ammattislangissa?

**Comment by eevajonnapanula** [comment]
Moikka, ootkohan muistanut commitata (se sen ikkunan alareunan "Commit changes"-lomake:)
![Commit-form](https://user-images.githubusercontent.com/28345294/96209351-0b006700-0f78-11eb-9cde-e7dff1261f67.png)

Kun oot sen tehnyt, sun täytyy vielä siitä repon "code"-välilehdeltä valita harmaasta laatikosta "Pull request":

![Comparison between fork and original repo](https://user-images.githubusercontent.com/28345294/96209357-0fc51b00-0f78-11eb-833f-5cce4b518f1f.png)

Tämän jälkeen avautuu ikkuna, josta vielä tarvitsee valita "Create pull request" (Vihreä painike, keltaisella pohjalla). Sen jälkeen aukeaa se ikkuna, missä kirjoitetaan, mitä PR:ssä on tehty :) Jos ei onnistu, laita vaikka tähän viestillä, mitä olet tehnyt/missä kohdin menee mönkään ja katsotaan mitä voidaan tehdä.

**Käännöksistä**: _Pull request_ on sana, jota käytetään ihan sellaisenaan myös suomeksi, joten sitä ei tarvitse kääntää. _Gotcha_ tässä tapauksessa on hieman hankala sana kääntää suoraan, ja kutsunkin @magdapoppins avuksi. (Taustaa: kyseessä on siis (Effective Python reading circlen)[https://github.com/turkupy/turkupy.github.io/blob/dev/content/events/fi/effective-python/index.md] suomennos).

**Comment by magdapoppins** [comment]
> Känsin yhden tekstin. Tulihan teksti perille? Siinä oli pari sanaa, joita en osannut suomentaa gotcha ja pull request, mitäköhän tämä on suomalaisessa ammattislangissa?

Pull request, kuten muunkin git-terminologian voi antaa olla ihan englanniksi. 
Olisiko gotcha suomeksi "jippo" tms?

**Comment by kzrantan** [comment]
Hei,

En löytänyt videota tuolta päivältä, enkä keksinyt miten koodia voi muokata
kun on jo kerran lähettänyt, joten painoin toisen pull requestin. Mutta
siellä on gotcha korjaamatta, toinen varmaan on ok suluissa.

Yt. Katri

pe 16. lokak. 2020 klo 8.20 Magda Stenius (notifications@github.com)
kirjoitti:

**Comment by eevajonnapanula** [comment]
Hmm, vieläkään ei näy tuo pull request meille. Laitan tähän parit ohjeet:

## Pull requestin tekeminen

1. Mene tähän osoitteeseen: https://github.com/kzrantan/turkupy.github.io/tree/patch-1 (silloin olet siinä branchissa, johon olet commitannut (eli tallentanut) ne muutokset, jotka olet tehnyt)
2. Klikkaa kuvassa punaisella ympyröityä painiketta:
<img width="952" alt="Screenshot 2020-10-20 at 16 21 36" src="https://user-images.githubusercontent.com/28345294/96591908-763b9780-12f0-11eb-911d-14e8a9f9c9ad.png">
3. Sen jälkeen pitäisi avautua sivu, jonka otsikkona on "Open a pull request". Tämän alta löytyy kenttä, jossa todennäköisesti lukee "Update index.md". Sen voisi muuttaa joksikin kuvaavammaksi (kuten "Translation to Effective Python reading circle"). Tämän alta löytyy isompi tekstikenttä, jossa on valmiina tekstiä: 
<img width="852" alt="Screenshot 2020-10-20 at 16 24 35" src="https://user-images.githubusercontent.com/28345294/96592161-c581c800-12f0-11eb-894d-eccc9921c138.png">

Siinä täytyy muokata tuota tekstiä (esim. olisi hyvä muuttaa tuo "Resolves # " muotoon "Resolves #35) ja kertoa, mitä PR:ssä on tehty. (Käytännössä siis tuo että olet kääntänyt tämän tapahtuman.)

4. Tuon isomman tekstikentän alta löytyy vihreä painike:
<img width="869" alt="Screenshot 2020-10-20 at 16 26 53" src="https://user-images.githubusercontent.com/28345294/96594931-cf58fa80-12f3-11eb-99c7-22879c5a8116.png">

Klikkaa sitä, ja sen jälkeen pull request on tehty. Voit vielä varmistaa, että se on tullut sillä tavalla, että katsot, että se löytyy tämän osoitteen takaa: https://github.com/turkupy/turkupy.github.io/pulls

## Muokkauksen tekeminen

1. Mene tiedostoon, jota haluat muokata. Esim. https://github.com/kzrantan/turkupy.github.io/blob/patch-1/content/events/fi/effective-python/index.md
2. Sieltä löytyy tuo punaisella ympyröity, painike, ja sitä klikkaamalla pääset muokkaustilaan
<img width="932" alt="Screenshot 2020-10-20 at 16 45 11" src="https://user-images.githubusercontent.com/28345294/96594888-c700bf80-12f3-11eb-9a37-00e87f7ec94c.png">

**Comment by kzrantan** [comment]
Nyt ilmeisesti tuli perille? Kiitos ohjeista!
