### ISSUE TITLE
[Translations] Turku.py goes data science! - fi

### ISSUE THREAD

**Issue by eevajonnapanula** [turkupy/turkupy.github.io#43]
**What event the translation is missing for:**
[Turku.py goes data science!](https://github.com/turkupy/turkupy.github.io/blob/dev/content/events/fi/turkupy-goes-datascience/index.md)

**Comment by magdapoppins** [comment]
Handing this ticket to @mialav ✨

**Comment by mialav** [comment]
Thanks @magdapoppins 😍
