### ISSUE TITLE
Add link to submit feature request into site footer

### ISSUE THREAD

**Issue by magdapoppins** [turkupy/turkupy.github.io#52]
**Is your feature request related to a problem? Please describe.**
I want to be able to submit a feature request to the site.

**Describe the solution you'd like**
I want to see a link on the front page and be able to make a feature request by clicking it.

**Describe alternatives you've considered**
Add a link.

**Additional context**
This could be added in the footer of the page.

**Comment by sifat009** [comment]
Hey, would you please clarify about the link? What should be the link?

**Comment by adhammo** [comment]
Hello, assign me to the issue, please. I have experience in React and Gatsby.js and would like to work on this.
