### ISSUE TITLE
Add a Meetabit link

### ISSUE THREAD

**Issue by lgrigoryeva1** [turkupy/turkupy.github.io#59]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
There should be a link to Turku.py's Meetabit page. The link could be similar to the existing Github and Twitter links in the footer. 

**Describe alternatives you've considered**
Another option would be to embed a Meetabit link in each post from the "Upcoming events" section. Although I think it's better to have a separate link on the home page.

**Comment by lgrigoryeva1** [comment]
@eevajonnapanula @magdapoppins

**Comment by eevajonnapanula** [comment]
yes! This is a good one.  So, as described, a link to Meetabit should be added to the footer. The link is https://meetabit.com/communities/turku-py

**Comment by eevajonnapanula** [comment]
This issue is reserved for the [Hacktoberfest-event](https://meetabit.com/events/turku-py-hacktoberfest)
