### ISSUE TITLE
Fix linking in fi- and sv-versions

### ISSUE THREAD

**Issue by eevajonnapanula** [turkupy/turkupy.github.io#65]
**Describe the bug**
When using the fi and sv-versions, the link in the header image leads to `/` instead of `/fi` or `/sv`.

**To Reproduce**
1. Go to `/fi` or `/sv`
2. Click the header image
3. You are now in the english site (so, `turkupy.github.io` or `localhost:8000` depending where you test)

**Expected behavior**
The link would lead to the correct site (so, `/fi` or  `/sv`)

**Suggestion to fix**
In the `Layout`-component, use the passed `langCode` to determinate if the link wrapping the header image is `/` or `/sv`or `/fi`. 

so for example:

```js
const indexPath = langCode === 'en' ? '/' : `/${langCode}`
```

**Comment by fandok** [comment]
i think i can take a look at this, can you assign the issue to me?

**Comment by eevajonnapanula** [comment]
Alright, thanks @fandok !

**Comment by fandok** [comment]
kindly check for the pull request @eevajonnapanula, many thanks!
